apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-js-app
  template:
    metadata:
      labels:
        app: node-js-app
    spec:
      containers:
      - name: node-js-container
        image: __IMAGE__  # Replaced by Jenkins during deployment
        ports:
        - containerPort: 3000